# Generated by Django 5.0.0 on 2024-06-24 12:00

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('senior', '시니어'), ('helper', '도우미')], max_length=10, verbose_name='역할')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='전화번호')),
                ('mileagePoints', models.PositiveIntegerField(default=0, verbose_name='마일리지 포인트')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='팀명')),
                ('logo', models.URLField(blank=True, verbose_name='로고 URL')),
                ('stadium', models.CharField(max_length=100, verbose_name='홈구장')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='경기일')),
                ('time', models.TimeField(verbose_name='경기 시간')),
                ('stadium', models.CharField(max_length=100, verbose_name='경기장')),
                ('awayTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='matching.team')),
                ('homeTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='matching.team')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='닉네임')),
                ('favorite_team', models.CharField(blank=True, max_length=50, verbose_name='관심 구단')),
                ('verification_info', models.CharField(blank=True, max_length=100, verbose_name='SNS 연동 or 팬클럽 ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('requestId', models.AutoField(primary_key=True, serialize=False)),
                ('gameDate', models.DateField(verbose_name='경기일')),
                ('gameTime', models.TimeField(verbose_name='경기 시간')),
                ('homeTeam', models.CharField(max_length=50, verbose_name='홈팀')),
                ('awayTeam', models.CharField(max_length=50, verbose_name='원정팀')),
                ('stadium', models.CharField(max_length=100, verbose_name='경기장')),
                ('seatType', models.CharField(max_length=50, verbose_name='좌석 유형')),
                ('accompanyType', models.CharField(choices=[('with', '함께 관람'), ('ticket_only', '티켓만 전달')], max_length=20, verbose_name='동행 유형')),
                ('additionalInfo', models.TextField(blank=True, verbose_name='추가 정보')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('accepted', '수락됨'), ('completed', '완료됨'), ('cancelled', '취소됨')], default='pending', max_length=20, verbose_name='상태')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('proposalId', models.AutoField(primary_key=True, serialize=False)),
                ('ticketInfo', models.CharField(max_length=200, verbose_name='티켓 정보')),
                ('message', models.TextField(blank=True, verbose_name='메시지')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('accepted', '수락됨'), ('rejected', '거절됨'), ('completed', '완료됨')], default='pending', max_length=20, verbose_name='상태')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('helperId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
                ('requestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='matching.request')),
            ],
        ),
    ]
