# Generated by Django 5.2.3 on 2025-06-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='numberOfTickets',
            field=models.IntegerField(default=1, verbose_name='티켓 수량'),
        ),
        migrations.AddField(
            model_name='team',
            name='string_id',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='문자열 ID'),
        ),
    ]
