# Generated by Django 5.2.3 on 2025-06-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_request_numberoftickets_team_string_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='string_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='문자열 ID'),
        ),
    ]
