# Generated by Django 5.2.3 on 2025-06-24 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_alter_team_string_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='matching.game'),
        ),
    ]
